"""End-to-end demo: greet the Dify.ai Longevity Mentor; agent replies via Gemma 4.

Drives the real **Dify chat web app** in a browser: types a greeting, waits for the
Longevity Mentor agent to respond, and asserts a non-empty reply — the reply is
generated by the local Gemma 4 model wired into Dify as its OpenAI-compatible
provider (see docs/longevity-coach/TODO-dify-local-gemma.md).

Prerequisites (all local): the Dify stack running (``nox -s dify``) with the
Longevity Mentor app published and its model provider pointed at the local
``llama-server``. Because that setup is not yet automated, this test **skips**
unless a reachable ``--dify-url`` is supplied — so it never breaks the pipeline:

    nox -s demo -- tests/end-to-end/test_dify_greeting_demo.py --dify-url http://localhost/chat/<app-id>
"""

from __future__ import annotations

import pytest
from playwright.sync_api import Page, expect

from _demo import make_narrator
from conftest import resolve_dify_url

pytestmark = pytest.mark.dify

GREETING = "Hello Longevity Mentor! Can you introduce yourself and confirm you are running locally?"


def _chat_input(page: Page):
    box = page.locator("textarea").first
    if box.count() == 0:
        box = page.get_by_role("textbox").first
    return box


def _open_chat(page: Page, dify_url: str):
    """Return Dify's public chat input, self-healing a poisoned session once.

    Dify's web API reads the webapp passport from a ``passport-<code>`` cookie
    *before* the fresh header token, so a single stale cookie from an earlier
    provisioning makes every ``/api/*`` call 401 — the chat then renders blank
    (no input) or redirects to ``/signin``. That is the "shows a login form"
    failure. Starting from a cleared session avoids it; if it still happens we
    wipe all client state and reload once before treating it as a real failure.
    """
    assert "/signin" not in page.url, f"Unexpected redirect to Dify login page: {page.url}"
    box = _chat_input(page)
    try:
        expect(box).to_be_visible(timeout=15000)
        return box
    except AssertionError:
        page.context.clear_cookies()
        page.evaluate("() => { try { localStorage.clear(); sessionStorage.clear(); } catch (e) {} }")
        page.goto(dify_url)
        page.wait_for_load_state("domcontentloaded")
        assert "/signin" not in page.url, f"Unexpected redirect to Dify login page: {page.url}"
        box = _chat_input(page)
        expect(box).to_be_visible(timeout=20000)
        return box


def test_dify_greeting_demo(page: Page, request) -> None:
    # The pipeline (`nox -s demo_dify`) provisions Dify and writes the app URL;
    # there is no skip — a missing/broken Dify dependency is a real failure.
    dify_url = resolve_dify_url(request.config)
    assert dify_url, (
        "No Dify Longevity Mentor URL. Run via `nox -s demo_dify` (which boots + "
        "provisions Dify), or pass --dify-url explicitly."
    )

    # Start from a guaranteed-clean session: a stale webapp passport cookie is the
    # root of the "login form / blank chat" failure this demo used to hit.
    page.context.clear_cookies()
    page.goto(dify_url)
    nar = make_narrator(page, request)  # Play/Pause + Next controls on the overlay
    nar("Dify · Longevity Mentor", "Opening the local Dify chat app for the Longevity Mentor agent…")
    page.wait_for_load_state("domcontentloaded")

    # Dify's chat app renders a textarea for input (self-heals a poisoned session).
    box = _open_chat(page, dify_url)

    nar("Greet the agent", f"Sending: “{GREETING}”")
    box.click()
    box.fill(GREETING)
    box.press("Enter")

    # The agent answers via the local Gemma 4 model — allow generous time for
    # on-device inference. Wait until an assistant reply of real length appears.
    nar("Awaiting Gemma 4", "The agent is responding using the on-device Gemma 4 model (no cloud)…", seconds=2.0)

    def _has_reply() -> bool:
        containers = page.locator(".chat-answer-container").all()
        return len(containers) > 0 and len(containers[-1].inner_text().strip()) > 15

    page.wait_for_function(
        """() => {
            const containers = document.querySelectorAll('.chat-answer-container');
            if (containers.length === 0) return false;
            const text = containers[containers.length - 1].innerText.trim();
            if (text.length < 15) return false;
            const streaming = Array.from(document.querySelectorAll('button')).some(b => (b.innerText || '').includes('Stop responding'));
            return !streaming;
        }""",
        timeout=180000,
    )
    assert _has_reply(), "Longevity Mentor agent did not produce a reply"

    nar("Reply received", "The Longevity Mentor greeted back — generated locally by Gemma 4.", seconds=3.0)
    nar.hold_open()  # demo: keep the window up until the presenter closes it
